name: Bug Report
description: Report a bug or unexpected behavior.
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior - use bullet points.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: If applicable, add any attachments that give context to the bug.
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Does the bug apply to VR, Desktop, or both?
      multiple: true
      options:
        - "VR"
        - "Desktop"
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add any other information about the bug here.
    validations:
      required: false
