name: Feature Request
description: Recommend a new feature or improvement.
type: Feature
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature or improvement you would like to see.
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: If applicable, add any attachments that give context to the feature request.
    validations:
      required: false
